---
title: "Plotly and Dashboard"
author: "Lizzy Gibson"
date: "November 1, 2017"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readr)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
#install.packages("plotly")
library(plotly)
#install.packages("flexdashboard")
library(flexdashboard)
```

## plot_ly

How you code it is similar to ggplot, different syntax.

## Dashboards

Clearly structured collection of graphics, plots, summaries.

flexdashboard is the R package, structured in R Markdown.

```{r}
airbnb_data <-  read_csv("./nyc_airbnb.csv") %>% 
  filter(neighbourhood_group == "Manhattan",
         room_type == "Entire home/apt",
         price > 100 & price < 400) 

airbnb_data %>%
  mutate(hover_text = str_c("Price: $", price, '\nRating: ', review_scores_location)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~hover_text)

```

\n tells R to put it on the next line.

### Boxplot

```{r}
airbnb_data %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(x = ~neighbourhood, y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")

common_neighborhoods =
  airbnb_data %>% 
  count(neighbourhood, sort = TRUE) %>% 
  top_n(8) %>% 
  select(neighbourhood)
## Selecting by n

inner_join(airbnb_data, common_neighborhoods,
             by = "neighbourhood") %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")
```

### Bar Chart

```{r}
airbnb_data %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```

### ggplot to plotly

```{r}
scatter_ggplot = airbnb_data %>%
  ggplot(aes(x = longitude, y = latitude, color = price)) +
  geom_point(alpha = 0.25) +
  scale_color_viridis() +
  coord_cartesian() +
  theme_classic()

ggplotly(scatter_ggplot)
```




