---
title: "Air BnB Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(readr)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)

airbnb_data <-  read_csv("./nyc_airbnb.csv") %>% 
  filter(neighbourhood_group == "Manhattan",
         room_type == "Entire home/apt",
         price > 100 & price < 400) 

#column width is out of 1000

# line tells it to start/create new column
```

Column {data-width=650} 
-----------------------------------------------------------------------

### Chart A

```{r}
airbnb_data %>%
  mutate(hover_text = str_c("Price: $", price, '\nRating: ', review_scores_location)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~hover_text)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
airbnb_data %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(x = ~neighbourhood, y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")
```

### Chart C

```{r}
airbnb_data %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```

